# Created by Alex Pereira

# Import Libraries
import cv2   as cv
import numpy as np
import transforms3d
import pupil_apriltags
from wpilib import Timer

# Import Classes
from Units               import Units
from Logger              import Logger
from AprilTag            import AprilTag
from AprilTagFieldLayout import AprilTagFieldLayout
from communications      import NetworkCommunications

# The size of the tag in meters
tagSize = Units.inchesToMeters(6)

# Creates the Detector Class
class Detector:
    def __init__(self) -> None:
        """
        Constructor for the Detector class.
        """
        # Creates all known AprilTags and stores them in a list
        allTags = self.createAllTags()

        # Instance creation
        self.commms = NetworkCommunications()
        self.field  = AprilTagFieldLayout(allTags, 2, 2, False)
        self.timer  = Timer()

        # Creates a pupil apriltags detector
        self.detector = pupil_apriltags.Detector(families = "tag16h5", nthreads = 16, quad_decimate = 1.0, quad_sigma = 0.0, refine_edges = 2.0, decode_sharpening = 1.00)

        # Update logs
        Logger.logInfo("Detector initialized")

    def detectTags(self, stream, camera_matrix, vizualization = 0, verbose = 0, annotate = False):
        """
        Detects AprilTags in a stream using dt_apriltags.
        @param stream: An images generated by reading a VideoCapture
        @param camera_matrix: The camera's calibration matrix
        @param vizualization: 0 - Highlight, 1 - Highlight + Boxes, 2 - Highlight + Axes, 3 - Highlight + Boxes + Axes
        @param verbose: 0 - Silent, 1 - Number of detections, 2 - Detection data, 3 - Detection and pose data
        @param annotate: Render annotated text on detection window
        @return detectionResult, image
        """
        # If the stream is not grayscale, create a grayscale version
        if (len(stream.shape) == 3):
            gray = cv.cvtColor(stream, cv.COLOR_BGR2GRAY)
        else:
            gray = stream

        # Define the intrinsic parameters of the camera
        intrinsic_properties = (camera_matrix[0, 0], camera_matrix[1, 1], camera_matrix[0, 2], camera_matrix[1, 2])  # fx, fy, cx, cy

        # Detect the AprilTags in the image with Duckie Town Apriltags
        detections = self.detector.detect(gray, estimate_tag_pose = True, camera_params = intrinsic_properties, tag_size = tagSize)

        # If verbose enabled, prints number of tags detected
        num_detections = len(detections)
        if (verbose == 1) or (verbose == 2) or (verbose == 3):
            print("Detected {} tags\n".format(num_detections))

        # Creates variables to use in detections
        results = []
        maxError = 1e-4
        minConfidence = 20

        # Access the 3D pose of all detected tag
        for i, tag in enumerate(detections):
            # Gets info from the tag
            decision_margin = tag.decision_margin
            hamming         = tag.hamming
            tag_num         = tag.tag_id
            center          = tag.center

            # Gets pose data from the tag
            rMatrix = tag.pose_R
            tVecs   = tag.pose_t
            err     = tag.pose_err

            # Throws out noise
            if ((hamming == 1) and (err <= maxError) and (decision_margin > minConfidence)):
                # Creates a 3d pose array from the rotation matrix and translation vectors
                pose = np.concatenate([rMatrix, tVecs], axis = 1)
            else:
                # Detected tag is noise, move to next detection
                continue

            # Prints debug info
            if (verbose == 2) or (verbose == 3):
                print( "Detection {} of {}:".format(i + 1, num_detections))
                print(tag.tostring(indent = 2))

            # Draws varying levels of information onto the image
            if (vizualization == 1):
                self.draw_pose_box(stream, camera_matrix, pose)
            elif (vizualization == 2):
                self.draw_pose_axes(stream, camera_matrix, pose, center)
            elif (vizualization == 3):
                self.draw_pose_box(stream, camera_matrix, pose)
                self.draw_pose_axes(stream, camera_matrix, pose, center)

            # Annotates the image
            if (annotate == True):
                self.annotate_detection(stream, tag)

            # Prints the Pose and calulated error
            if (verbose == 3):
                print("Pose: \n", pose, "\nPoseError: \n", err)

            # Calculate Euler's Angles
            euler_angles = self.calculateEulerAngles(pose[:3, :3])

            # Adds results to the array
            results.extend([tag_num, err, pose, euler_angles])

            # Updates log
            Logger.logInfo("Tag: {}, \nrMatrix: \n{}, \ntVecs: \n{}, \nEuler Angles: \n{}, \nPose3d: \n{}".format(tag_num, pose[:3, :3], pose[:3, 3:], euler_angles, pose))

        # Gets current time
        time = self.timer.getFPGATimestamp()

        # Sets detection time
        self.commms.sendDetectTimeSec(time)

        return results, stream

    def undistort(self, stream, cameraMatrix, distortion, resolution: tuple):
        """
        Undistorts an image using cv.undistort()
        @param stream
        @param cameraMatrix
        @param cameraDistortion
        @param cameraResolution (width, height)
        @return undistortedStream
        """
        # Creates a cameraMatrix
        newCameraMatrix, roi = cv.getOptimalNewCameraMatrix(cameraMatrix, distortion, resolution, 1, resolution)

        # Undistorts the image
        undistortedStream = cv.undistort(stream, cameraMatrix, distortion, None, newCameraMatrix)

        # Crops the image
        x, y, w, h = roi
        undistortedStream = undistortedStream[y:y+h, x:x+w]

        return undistortedStream

    def calculateEulerAngles(self, rotationalMatrix):
        """
        Calculates Euler's Angles from a rotationMatrix
        @param rotationMatrix
        @return euler_angles_degrees
        """
        # Extract the tag data from the detection results
        if rotationalMatrix is not None:
            # Convert the rotation matrix to Euler angles using the sxyz convention
            euler_angles = transforms3d.euler.mat2euler(rotationalMatrix, "sxyz")

            # Convert the tuple of Euler angles to a NumPy array
            euler_angles = np.array(euler_angles)

            # Convert the Euler angles from radians to degrees
            # euler_angles = euler_angles * 180/np.pi

            return euler_angles
        else:
            # Returns an array of zeros
            return np.zeros(3)

    def draw_pose_box(self, img, camera_matrix, pose, z_sign = 1):
        """
        Draws the 3d pose box around the AprilTag.
        @param img: The image to write on
        @param camera_matrix: The camera's calibration matrix
        @param pose: The 3d pose of the tag
        @param z_sign: The direction of the z-axis
        """
        # Creates object points
        opoints = np.array([
            -1, -1, 0,
            1, -1, 0,
            1,  1, 0,
            -1,  1, 0,
            -1, -1, -2 * z_sign,
            1, -1, -2 * z_sign,
            1,  1, -2 * z_sign,
            -1,  1, -2 * z_sign,
        ]).reshape(-1, 1, 3) * 0.5 * tagSize

        # Creates edges
        edges = np.array([
            0, 1,
            1, 2,
            2, 3,
            3, 0,
            0, 4,
            1, 5,
            2, 6,
            3, 7,
            4, 5,
            5, 6,
            6, 7,
            7, 4
        ]).reshape(-1, 2)

        # Calulcates rotation and translation vectors for each AprilTag
        rVecs, _ = cv.Rodrigues(pose[:3,:3])
        tVecs = pose[:3, 3:]

        # Derivative coefficients
        dcoeffs = np.zeros(5)

        # Calulate image points of each AprilTag
        ipoints, _ = cv.projectPoints(opoints, rVecs, tVecs, camera_matrix, dcoeffs)
        ipoints = np.round(ipoints).astype(int)
        ipoints = [tuple(pt) for pt in ipoints.reshape(-1, 2)]

        # Draws lines between all the edges
        for i, j in edges:
            cv.line(img, ipoints[i], ipoints[j], (0, 255, 0), 1, 16)

    def draw_pose_axes(self, img, camera_matrix, pose, center):
        """
        Draws the colored pose axes around the AprilTag.
        @param img: The image to write on
        @param camera_matrix: The camera's calibration matrix
        @param pose: The 3d pose of the tag
        @param center: The center of the AprilTag
        """
        # Calulcates rotation and translation vectors for each AprilTag
        rVecs, _ = cv.Rodrigues(pose[:3,:3])
        tVecs    = pose[:3, 3:]

        # Derivative coefficients
        dcoeffs = np.zeros(5)

        # Calculate object points of each AprilTag
        opoints = np.float32([[1, 0, 0],
                              [0, -1, 0],
                              [0, 0, -1]]).reshape(-1, 3) * tagSize

        # Calulate image points of each AprilTag
        ipoints, _ = cv.projectPoints(opoints, rVecs, tVecs, camera_matrix, dcoeffs)
        ipoints = np.round(ipoints).astype(int)

        # Calulates the center
        center = np.round(center).astype(int)
        center = tuple(center.ravel())

        # Draws the 3d pose lines
        cv.line(img, center, tuple(ipoints[0].ravel()), (0,0,255), 2)
        cv.line(img, center, tuple(ipoints[1].ravel()), (0,255,0), 2)
        cv.line(img, center, tuple(ipoints[2].ravel()), (255,0,0), 2)

    def annotate_detection(self, img, tag):
        """
        Annotates the image with coordinates.
        @param img: The image to write on
        @param detection: A detected AprilTag in the image
        """
        # Sets font
        font = cv.FONT_HERSHEY_SIMPLEX

        # Gets the tag properties
        text = str(tag.tag_id)
        tag_center = [tag.center[0], tag.center[1]]

        # Calulates the inner tag size
        tag_size_px = np.sqrt((tag.corners[1][0] - tag.corners[0][0]) ** 2 + (tag.corners[1][1] - tag.corners[0][1]) ** 2)

        # Gets font and text size
        font_size = tag_size_px / 22
        text_size = cv.getTextSize(text, font, font_size, 2)[0]

        # Gets the text position
        text_x = int(tag_center[0] - text_size[0] / 2)
        text_y = int(tag_center[1] + text_size[1] / 2)

        # Writes the text to the image
        cv.putText(img, text, (text_x, text_y), font, font_size, (0, 255, 255), 2)
    
    def createAllTags(self):
        """
        Creates all known AprilTags.
        @return allKnownTags: An array with all the known tags contained in it
        """
        allKnownTags = [
            AprilTag(0, 1, 1, 1, 1, 1, 1)
        ]

        return allKnownTags